loading data
Begin training
fold: 1
Traceback (most recent call last):
  File "/mnt/c/Users/susan/git/HEA-Toxicity-Prediction/runner.py", line 110, in <module>
    train_loss = do_epoch(model, device, train_loader, True, optimizer=optimizer)
  File "/mnt/c/Users/susan/git/HEA-Toxicity-Prediction/runner.py", line 72, in do_epoch
    pred_result = model(input)
  File "/home/susan/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/c/Users/susan/git/HEA-Toxicity-Prediction/neural_network.py", line 34, in forward
    x = self.relu(self.hidden_layers[i](x))
  File "/home/susan/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/susan/.local/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat1 in method wrapper_addmm)